# 订阅源：保留所有你添加的链接，无语法错误
subs:
  # 自动聚合源
  - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_Sub.txt
  - https://raw.githubusercontent.com/ermaozi01/free_nodes/main/Clash/20260213.yaml
  - https://raw.githubusercontent.com/mian2018/free/main/v2ray
  - https://raw.githubusercontent.com/free18cm/V2rayCollector/main/reality/sub.txt
  - https://raw.githubusercontent.com/darknessmk27/ranconfigcollector/main/bulk/vless_iran.txt
  - https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yaml
  - https://raw.githubusercontent.com/dongchengjie/airport/heads/main/clash.yaml
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
  # 自定义订阅链接
  - https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
  - https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml
  - https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml
  - https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/main/all_configs.txt
  - https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml
  - https://raw.githubusercontent.com/Roywaller/clash_subscription/main/clash_subscription.txt
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc0.yaml
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc1.yaml
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc2.yaml
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc3.yaml
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc4.yaml
  - https://raw.githubusercontent.com/xiaoji235/airport-free/main/clash/naidounode.txt
  - https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml
  - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml
  - https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
  - https://raw.githubusercontent.com/leetomlee123/freenode/main/README.md
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
  - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
  - https://raw.githubusercontent.com/mgit0001/test_clash/main/heima.txt
  - https://raw.githubusercontent.com/mai19950/clashgithub_com/main/site
  - https://raw.githubusercontent.com/mai19950/sites/main/sub/v2ray/base64
  - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
  - https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
  - https://raw.githubusercontent.com/shahidbhutta/Clash/main/Router
  - https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
  - https://raw.githubusercontent.com/free18/v2ray/main/c.yaml
  - https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  - https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
  - https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
  - https://raw.githubusercontent.com/xiaoji235/airport-free/main/v2ray.txt
  - https://raw.githubusercontent.com/vxiaov/free_proxies/main/links.txt
  - https://raw.githubusercontent.com/xiaoji235/airport-free/main/v2ray/v2rayshare.txt
  - https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/all.yaml
  - https://raw.githubusercontent.com/ts-sf/fly/main/clash
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/yudou66.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/clashmeta.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/ndnode.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/nodev2ray.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/nodefree.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/v2rayshare.txt
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/wenode.txt
  - https://raw.githubusercontent.com/ggborr/FREEE-VPN/main/4V2ray
  - https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links1.txt
  - https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links2.txt
  - https://raw.githubusercontent.com/acymz/AutoVPN/main/data/V2.txt
  - https://raw.githubusercontent.com/peacefish/nodefree/main/sub/proxy_cf.yaml
  - https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/V2.txt
  - https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/utils/pool/output.yaml
  - https://raw.githubusercontent.com/yorkLiu/FreeV2RayNode/main/v2ray.txt
  - https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/ss.txt
  - https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/ssr.txt
  - https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/trojan.txt
  - https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/vless.txt
  - https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/vmess.txt
  - https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/Clash.yaml
  - https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/trinity_clash.yaml
  - https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/VM_TrinityBase
  - https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/TrinityBase
  - https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/ss_iran.txt
  - https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/trojan_iran.txt
  - https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/vless_iran.txt
  - https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/vmess_iran.txt
  - https://raw.githubusercontent.com/dongchengjie/airport/refs/heads/main/subs/merged/tested_within.yaml
  - https://raw.githubusercontent.com/openrunner/clash-freenode/main/clash.yaml
  - https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml
  - https://raw.githubusercontent.com/free-nodes/clashfree/main/clash20260212.yml
  - https://raw.githubusercontent.com/Enibels/get_proxy/main/dist/clash.config.yaml
  - https://github.com/dongchengjie/airport
  - https://github.com/lza6/free-VPN
  - https://raw.githubusercontent.com/free-nodes/v2rayfree/main/v202602132.txt
  - https://github.com/free-nodes/v2rayfree
  - https://github.com/barry-far/V2ray-Config
  - https://github.com/free-nodes/clashfree
  - https://raw.githubusercontent.com/barry-far/V2ray-Config/main/All_Configs_Sub.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Config/main/Sub1.txt
  - https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_Sub.txt
  - https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/all_extracted_configs.txt
  - https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/subscriptions/v2ray/all_sub.txt
  - https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/subscriptions/v2ray/super-sub.txt
  - https://raw.githubusercontent.com/DaBao-Lee/V2RayN-NodeShare/main/base64
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
  - https://raw.githubusercontent.com/free-nodes/v2rayfree/main/v202602132
  - https://github.com/Epodonios/v2ray-configs
  - https://raw.githubusercontent.com/skywolf627/VmessActions/main/clash.yml
  - https://raw.githubusercontent.com/LonUp/NodeList/main/TempConfigs/Clash/004.yaml
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/

# 全局筛选：仅保留trojan/vless协议，延迟<150ms
global_filter:
  - type: include
    protocol: trojan|vless
  - type: exclude
    delay: ">150"

# 多输出：生成4个独立订阅文件（港/新/日/综合）
outputs:
  - name: 香港节点专用
    file: sub_hk.yaml
    type: yaml
    filter:
      - type: include
        keyword: 香港|hk
  - name: 新加坡节点专用
    file: sub_sg.yaml
    type: yaml
    filter:
      - type: include
        keyword: 新加坡|sg
  - name: 日本节点专用
    file: sub_jp.yaml
    type: yaml
    filter:
      - type: include
        keyword: 日本|jp
  - name: 港新日综合节点
    file: sub_all.yaml
    type: yaml
    filter:
      - type: include
        keyword: 香港|hk|新加坡|sg|日本|jp
