subs:
  - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_Sub.txt
  - https://raw.githubusercontent.com/ermaozi01/free_nodes/main/Clash/20260213.yaml
  - https://raw.githubusercontent.com/mian2018/free/main/v2ray
  - https://raw.githubusercontent.com/free18cm/V2rayCollector/main/reality/sub.txt
  - https://raw.githubusercontent.com/darknessmk27/ranconfigcollector/main/bulk/vless_iran.txt
  - https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yaml
  - https://raw.githubusercontent.com/dongchengjie/airport/heads/main/clash.yaml
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
  - https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
  - https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml
  - https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml
  - https://raw.githubusercontent.com/Roywaller/clash_subscription/main/clash_subscription.txt
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc0.yaml
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc1.yaml
  - https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/main/APIs/sc2.yaml
  - https://raw.githubusercontent.com/xiaoji235/airport-free/main/clash/naidounode.txt
  - https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml
  - https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
  - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
  - https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
  - https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
  - https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
  - https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/all.yaml
  - https://raw.githubusercontent.com/ts-sf/fly/main/clash
  - https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/clashmeta.txt
  - https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/trojan.txt
  - https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/Clash.yaml
  - https://raw.githubusercontent.com/openrunner/clash-freenode/main/clash.yaml
  - https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml
  - https://raw.githubusercontent.com/barry-far/V2ray-Config/main/All_Configs_Sub.txt
  - https://raw.githubusercontent.com/skywolf627/VmessActions/main/clash.yml

# 重点：只保留 trojan
global_filter:
  allowed_protocols: ["trojan"]
  max_delay: 150
